- name: backend
  hosts: backend
  become: yes
  tasks:
  - name: remove default nodejs
    ansible.builtin.command: dnf module list installed nodejs 
    

    # - name: nodejs installation
    #   ansible.builtin.package:
    #     name: "{{ item }}"
    #     state: present
    #   loop:
    #   - nodejs
    #   - mysql
    
    
