- name: Mysql tier
  hosts: mysql
  become: yes
  vars:   
    login_host: mysql.dev-ops81s.online  #host
    mysql_root_password: ExpenseApp@1    
  tasks:
  - name: ansible to install pymysql
    ansible.builtin.pip:
      name:
      - PyMySQL
      executable: pip3.9

  - name: Mysql installation
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: Mysql starting
    ansible.builtin.service:
      name: mysql-server
      state: started
      enabled: yes

  - name: mysql setup
    community.mysql.mysql_info:
      login_user: root
      login_host: "{{ login_host }}"
      login_password: "{{ mysql_root_password }}"
    ignore_errors: true
    register: mysql_info

  - name: print mysql info
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"

  - name: setup MySQL root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: mysql_info.failed is true
   
  
  
  